# Generated by Django 5.2.7 on 2025-10-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Tour Operator'), ('tourist', 'Tourist')], default='tourist', help_text='Designates the role of the user in the platform.', max_length=20),
        ),
    ]
