# Generated by Django 5.2.7 on 2025-10-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Tour Operator')], default='operator', help_text='Designates the role of the user in the platform.', max_length=20),
        ),
    ]
