# Generated by Django 5.2.7 on 2025-11-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('owner_full_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('contact_person_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_phone', models.CharField(blank=True, max_length=30)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('association_certificate', models.FileField(blank=True, null=True, upload_to='supplier_certificates/')),
                ('business_certificate', models.FileField(blank=True, null=True, upload_to='supplier_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
