# Generated by Django 5.2.7 on 2026-03-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceavailability_servicetimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceavailability',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
