# Generated by Django 5.2.7 on 2026-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceavailability_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tour_inclusive',
            field=models.TextField(blank=True, default=''),
        ),
    ]
