# Generated by Django 5.2.7 on 2026-01-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0004_serviceavailability_servicetimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Specific time slot booked', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.servicetimeslot'),
        ),
    ]
