# Generated by Django 5.2.7 on 2026-03-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_description_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_duration_hours_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_inclusive_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
