# Generated by Django 5.2.7 on 2026-03-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_service_description_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final booked amount at the time the booking was created.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
