# Generated by Django 5.2.7 on 2026-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_final_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_qr_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token used for booking QR verification.', max_length=255, null=True, unique=True),
        ),
    ]
