# Generated by Django 5.2.7 on 2026-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_booking_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_card_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License'), ('employment_id', 'Employment ID')], max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
